services:
  syr-dev:
    build:
      context: .
      dockerfile: docker/dev/syr.dockerfile
    ports:
      - "${PORT:-5173}:${PORT:-5173}"
    env_file:
      - .env
    environment:
      - PORT=${PORT:-5173}
    stdin_open: true
    tty: true
    develop:
      watch:
        # Sync entire app directory for hot reload
        - action: sync
          path: ./apps/syr
          target: /app/apps/syr
          ignore:
            - node_modules/
            - "**/*.swp"
            - "**/.DS_Store"
            - .svelte-kit/
            - build/
            - package.json
        
        # Rebuild when workspace configuration changes
        - action: rebuild
          path: ./package.json
        
        - action: rebuild
          path: ./pnpm-lock.yaml
        
        - action: rebuild
          path: ./pnpm-workspace.yaml
        
        - action: rebuild
          path: ./turbo.json
        
        # Rebuild when app dependencies change
        - action: rebuild
          path: ./apps/syr/package.json


