[package]
name = "syner"
version = "0.1.0"
description = "Syr Persona Manager"
authors = ["SoSweetHam <sosweetham@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "syner_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
syr-crypto-core = { path = "../../../../packages/rust/syr-crypto-core" }
syr-crypto-sigil = { path = "../../../../packages/rust/syr-crypto-sigil" }
base64 = "0.21"
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
dirs = "5"
chrono = "0.4"
zip = "2"

