blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/syr-is/syr/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/syr-is/syr/blob/main/README.md
    about: Read the project documentation
