#!/bin/sh
set -e
echo "Building..."
pnpm run build
echo "Running format, lint, check, test..."
pnpm run format
pnpm run lint
pnpm run check
pnpm run test
echo "Running cargo format check and clippy..."
pnpm run cargo:format:check
pnpm run cargo:clippy
