name: Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-dev:
    name: Dev Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/dev/syr.dockerfile
          push: false
          tags: syr-dev:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max

  docker-prod:
    name: Prod Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/prod/syr.dockerfile
          push: false
          tags: syr-prod:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max

